# Generated by Django 4.2.3 on 2023-07-31 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("practice_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=100)),
                ("added_date", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(max_length=10)),
                ("about", models.TextField()),
                (
                    "positon",
                    models.CharField(
                        choices=[
                            ("Junior Backend Developer", "Junior Backend Developer"),
                            ("Senior Bakend Developer", "Senior Backend Developer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="practice_api.company",
                    ),
                ),
            ],
        ),
    ]
